### ISSUE TITLE
Expose events to clients

### ISSUE THREAD

**Issue by thinktainer** [pebblecode/wfh2_backend#7]
We could expose a live stream of user's interactions with the system. This could be used by clients to have something similar to a stock ticker with live updates coming through. The `gen_event` master is already existing in the code, this is only a matter of hooking up a publish mechanism through websockets or SPDY, or maybe an Atom (RSS) feed.

**Comment by export-mike** [comment]
😢

**Comment by thinktainer** [comment]
Hey, miss the fun times, how's you?

**Comment by export-mike** [comment]
@thinktainer yeah me too! forever trying to replicate the culture! its not the same! haha

All good thanks! I live in Sydney Australia now, mostly the same stack haha nothings changed! 

Hope all is well! hows things?

**Comment by export-mike** [comment]
@thinktainer https://join.slack.com/t/pebble-space-code/shared_invite/enQtNzc3ODQ0NzE1MDQ2LTg3ZDhlYjk1YjJlNWQyMzFlOWM2OGRhNzY5MTFkNDI1ZjE4YzM1YjEyMTkxNmQ2MmFhYmY2MmFjZGJkMjcyMjU
